[PHP]
; Custom PHP configuration for this project
memory_limit = -1
max_execution_time = 0
error_reporting = E_ALL
display_errors = 1
default_charset = "UTF-8"
date.timezone = "UTC"
extension_dir = "C:\Program Files\php-8.5.3\ext"
extension=curl
extension=fileinfo
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=zip
